### ISSUE TITLE
Contact Display in mdEditor in "Point of Contacts" section

### ISSUE THREAD

**Issue by mmheller** [adiwg/mdEditor#166]
Problem: Attached is a mdEditor file Eric is having issues with.  Eric brought me in to troubleshoot injector script topics but we uncovered an issue with an mdEditor file before touched with the injector script.  The contacts in the mdEditor "Point of Contacts" section are not displaying (however the Role is displaying).

Symptoms:  The attached mdEditor file imports however the Point of Contact section is hit or miss.  Looking at the JSON view shows values however the text description for the values are not always showing up in mdEditor.  Should we be concerned with this?  Any help is appreciated.

![image](https://user-images.githubusercontent.com/6976696/35122841-62fb3aa6-fc5d-11e7-9c66-a1035b4078dd.png)

![image](https://user-images.githubusercontent.com/6976696/35122848-694c7348-fc5d-11e7-8435-6b3c3e3b5819.png)

![image](https://user-images.githubusercontent.com/6976696/35122862-778c877c-fc5d-11e7-9244-d3c6a0f1afc5.png)

![image](https://user-images.githubusercontent.com/6976696/35122872-7e629f82-fc5d-11e7-97d6-36178a5b339c.png)

[joshInspect-prj407.zip](https://github.com/adiwg/mdEditor/files/1644543/joshInspect-prj407.zip)
**mdEditor Version:   0.0.0+567cc8c5

**mdEditor Web Address:  https://jlblcc.github.io/mdEditor/#/dashboard

**Comment by jlblcc** [comment]
This should be fixed in jlblcc/mdEditor. This affected the display only. The selected contact ids are still present. Before the bug fix, if you exit the parent route, e.g. go to the dashboard, and navigate back, the contact should be displayed. That's why it appears to display inconsistently. I won't bore you with the technical details, check the commit message for that.
