### ISSUE TITLE
In Distribution, cannot edit or delete online option after creation

### ISSUE THREAD

**Issue by akeister** [adiwg/mdEditor#239]
## Issue
**mdEditor Version** (find version under settings): 
0.5.0+743fd53a

**mdEditor Web Address** (enter the URL):
https://go.mdeditor.org

### Issue Description:
I entered online options under distribution, but I realized I forgot to add that it is a "download" under the "function" field. I went back to add that, but I can't figure out how to edit the existing online option. I also can't figure out how to delete the online option and start again. I've attached 2 screenshots of what I'm seeing. 

![distributiontop](https://user-images.githubusercontent.com/31963773/47368861-70366000-d6b0-11e8-9d16-71dc16301b9a.JPG)
![distributiononline](https://user-images.githubusercontent.com/31963773/47368870-73c9e700-d6b0-11e8-9825-f91fc5331aab.JPG)

**Comment by jlblcc** [comment]
This is caused by the length of the URL. The browser is treating it as one long word, so it's not being wrapped. I'll make a modification so that the URL is truncated if it cannot fit within the available space.

![image](https://user-images.githubusercontent.com/5833603/47384202-e8058a00-d6b2-11e8-8561-b900ba8f23d2.png)

**Comment by akeister** [comment]
Thank you Josh!
