### ISSUE TITLE
Metadata Repositories potential bug

### ISSUE THREAD

**Issue by lamcduffie** [adiwg/mdEditor#368]
An error occurs when a metadata repositories record is added to project metadata: 
![Capture](https://user-images.githubusercontent.com/26660466/72186316-768e2600-33a1-11ea-8337-5f4e06b41261.JPG)

There is no way to edit the repository record to include a title beyond the collection title:
![Capture](https://user-images.githubusercontent.com/26660466/72186426-b6550d80-33a1-11ea-8d16-9495445ffd55.JPG)

Maybe I'm missing something??

**Comment by jlblcc** [comment]
Nope, that's a bug 🐞. Actually a typo: `titles` should be `title`:

https://github.com/adiwg/mdEditor/blob/fb5676510b77c32d7d85ae6d8f802dd82fead22c/app/pods/components/object/md-repository-array/template.hbs#L26

We'll get this patched and out in 0.11.0 which should be released next week. If you need it right away, I can push the fix to https://dev.mdeditor.org (you'll need to import your records due to the domain change).

**Comment by jlblcc** [comment]
Pushed to https://dev.mdeditor.org/ in 0.10.0.rc3
