### ISSUE TITLE
Taxonomy tab missing categories in "project" profile

### ISSUE THREAD

**Issue by lamcduffie** [adiwg/mdEditor#369]
Should the Taxonomy tab under the "project" profile contain the same categories as the Taxonomy tab under the "products" profile? According to the Alaska Region Metadata Guide, project and product should be identical.

Project looks like this: 
![image](https://user-images.githubusercontent.com/26660466/72191732-aa704800-33af-11ea-9dbd-e8b37f0a8a32.png)

Product looks like this:
![image](https://user-images.githubusercontent.com/26660466/72191756-c2e06280-33af-11ea-9a27-e59430c7f991.png)

**Comment by jlblcc** [comment]
The default profiles are meant to be generic, not specific to one organization. There is support for custom profiles that can be created to suit specific needs or requirements. A profile can be created to meet the specific needs of the https://ak-region-dst.gitbook.io/alaska-region-mdeditor-interim-user-guide/.

The difference in the default `project` and `product`profiles is intentional. The assumption made here is that in most use cases the project-level metadata will not need to include information about specific sampling events (i.e. the elements Observer, General Scope, Procedure, etc...), but would mainly be concerned with associating taxa with the project.

**Comment by hmaier-fws** [comment]
Resolved as general user support issue.
